/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:d50d967b-5060-4ee6-9a38-708a0a429d5a",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_5PeIqZRAj",
    "aws_user_pools_web_client_id": "16c087nas194mlv6om7vjn32sa",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://grezjaqx4rf3xl4kb4hwvsixaq.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
